name: Package

on:
  push:
    branches: [main, master]
    tags:
      - '!updater'
      - '*.*.*'
  workflow_dispatch:

jobs:
  change-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.outputstep.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - id: outputstep
        run: |
          RAW_VERSION=$(git describe --tags | sed 's/-[0-9]*-.*//g')
          VERSION=${RAW_VERSION#v}
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Change Version for Windows
        run: |
          VERSION=$(git describe --tags | sed 's/-[0-9]*-.*//g' | sed 's/^v//')
          sed -i "s/\"version\":.*/\"version\": \"$VERSION\",/g" package.json
          sed -i "s/\"version\":.*/\"version\": \"$VERSION\"/g" src-tauri/tauri.conf.json
          sed -i "s/version = \"0.0.0\"/version = \"$VERSION\"/g" src-tauri/Cargo.toml

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: ./*
          if-no-files-found: error

  build-for-windows:
    needs: change-version
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Decode private key
        shell: pwsh
        run: |
          $base64 = "${{ secrets.TAURI_PRIVATE_KEY }}"
          $bytes = [System.Convert]::FromBase64String($base64)
          [System.IO.File]::WriteAllBytes("cheatsheet.key", $bytes)

      - name: Build Tauri app (NSIS + updater)
        env:
          TAURI_PRIVATE_KEY: "cheatsheet.key"
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: pnpm tauri build -b nsis,updater --target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_x86_64
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG
          token: ${{ secrets.GITHUB_TOKEN }}
          files: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*setup*